packages:
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi

syncInjectedDepsAfterScripts:
  - build
